#!/usr/bin/env python3
"""Make PyInstaller bundle every first-party module, under both import roots.

PyInstaller finds modules by reading import statements. Anything the program
loads by *name* at runtime is invisible to it, and this codebase does that a
lot:

  - 26 top-level compatibility shims, e.g. market_data_client.py, which is
        sys.modules[__name__] = import_module("clients.market_data_client")
  - brokers/registry.py, which imports each broker adapter from a table
  - agents/registry.py, which imports 31 agents from a table

Inspected, the v0.56.0 macOS binary contained none of the 26 shim targets, 1 of
10 broker adapters (paper trading only) and 8 of 31 agents. Every one of those
loaders catches the ImportError and logs it at debug level, so nothing failed:
`quote` fell back to a backend at localhost:8000, the broker list was just
shorter, and the warehouse and realty agents were simply absent.

Why not --collect-submodules: it was tried first, and it does not work for
this tree. It discovers submodules by importing the package in an isolated
process that does not see --paths, so `--collect-submodules clients` found
the packaged `aria_code.clients.*` and not the bare `clients.*` that the shims
import — the binary built, looked complete, and `quote` still failed. A
diagnostic build importing `market_data_client` reproduced it exactly:
"No module named 'clients.market_data_client'".

So this walks the source tree instead of importing it, and lists every module
under both roots: bare (`clients.market_data_client`, what shims and the
broker table use) and packaged (`aria_code.clients.market_data_client`). That
is ~940 names — too long for a Windows command line — so they go into a
PyInstaller hook for the `aria_code` package. A hook only runs when its
module is imported, and an entry script that never imports `aria_code` would
silently skip all of it (a diagnostic build did exactly that), so this also
names `aria_code` as a hidden import. It prints:

    --additional-hooks-dir <dir>
    --hidden-import aria_code

It also excludes the modules in EXCLUDED, which are installed but must not be
frozen.

Printed one token per line, so it splices correctly into bash and PowerShell
`$(...)` alike.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "src" / "aria_code"
HOOKS_DIR = ROOT / "build" / "pyinstaller-hooks"

# pandas_ta imports numba at module level, and numba brings llvmlite: an LLVM
# build that was 133 MB of the 468 MB Linux binary, 42 MB of it compressed.
# That pushed the linux-x64 npm package to 201.6 MB packed; npm's publish
# body is the tarball base64-encoded, so 268.7 MB against a 256 MiB limit,
# and v0.59.0 was rejected (linux-arm64, 195.9 MB, got through).
#
# The binary used pandas_ta for one thing: RSI in the factor tool, which has a
# pandas fallback. Python the user runs goes to their own interpreter, not the
# frozen one, so nothing they write loses pandas_ta. pip installs keep it.
EXCLUDED = ("pandas_ta", "numba", "llvmlite")


def _is_module(path: Path) -> bool:
    return path.suffix == ".py" and "__pycache__" not in path.parts


def bare_module_names() -> list[str]:
    """Every module under src/aria_code, named as the bare root imports it."""
    names: set[str] = set()
    for path in PACKAGE.rglob("*.py"):
        if not _is_module(path):
            continue
        relative = path.relative_to(PACKAGE).with_suffix("")
        parts = list(relative.parts)
        # Only modules reachable as packages: every parent directory must have
        # an __init__.py, or the module is not importable by a dotted name.
        if any(not (PACKAGE.joinpath(*parts[:i]) / "__init__.py").is_file() for i in range(1, len(parts))):
            continue
        if parts[-1] == "__init__":
            parts = parts[:-1]
        if parts:
            names.add(".".join(parts))
    return sorted(names)


def hidden_imports() -> list[str]:
    bare = bare_module_names()
    return sorted(set(bare) | {f"aria_code.{name}" for name in bare} | {"aria_code"})


def write_hook(directory: Path = HOOKS_DIR) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    hook = directory / "hook-aria_code.py"
    names = hidden_imports()
    datas = [(str(PACKAGE / "ui" / "assets" / "aria-robot.png"), dest)
             for dest in ("aria_code/ui/assets", "ui/assets")]
    hook.write_text(
        "# Generated by scripts/pyinstaller_collect_args.py — do not edit.\n"
        "# Every first-party module under both import roots; see that script.\n"
        f"hiddenimports = {names!r}\n"
        # Both roots are imported by the compatibility bootstrap. Data must
        # sit beside whichever module __file__ the renderer resolves.
        f"datas = {datas!r}\n",
        encoding="utf-8",
    )
    return directory


def collect_args() -> list[str]:
    # Relative to the working directory: both callers build from the repo
    # root, and an absolute path with a space in it ("Application Support")
    # would be split in two by the unquoted $(...) that splices this in.
    args = ["--additional-hooks-dir", os.path.relpath(write_hook()),
            "--hidden-import", "aria_code"]
    for module in EXCLUDED:
        args += ["--exclude-module", module]
    return args


def main() -> int:
    print("\n".join(collect_args()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
